### ISSUE TITLE
onAnimationFinish not being called

### ISSUE THREAD

**Issue by bernardodesousa** [react-native-web-community/react-native-web-lottie#23]
Hey there! I'm calling setState from the onAnimationFinish function, but it's not being fired. The animation plays to the end, then nothing happens. I tried just calling a console.log from there instead of setting the state, just in case. It's really not being called.

Works fine on mobile thou (lottie-react-native 3.4.0). Is anyone else experiencing that?

**Comment by bernardodesousa** [comment]
Hey again! I looked into the code and it would seem the fix is pretty straightforward. Please take a look at https://github.com/react-native-web-community/react-native-web-lottie/pull/24 to see if it's not against the projects code style/architecture rules or something. This is my first PR on an open source project so it's likely to contain some rookie mistake. Feel free to point it out to me. I'd be glad!

**Comment by Minishlink** [comment]
Hello, thanks for your contribution, it's published in 1.4.2 :)
