### ISSUE TITLE
Does it run on Expo?

### ISSUE THREAD

**Issue by mafiusu** [react-native-web-community/react-native-web-lottie#33]
This is no real issue but I was asking myself if this library could work with expo web. Since expo uses internally react-native-web. Has anyone experienced this and can tell me how to get it to work?

**Comment by farhanalislalom** [comment]
I am stuck on the same issue. Can't get it to work on the web but it works fine on mobile. Also, VSCode is displaying an error about type definitions for react-native-web-lottie.
