### ISSUE TITLE
resizeMode='cover' does not work

### ISSUE THREAD

**Issue by l2aelba** [react-native-web-community/react-native-web-lottie#58]
**Example:**
```
<LottieView resizeMode='cover' ... />
````

In SVG it's still

`preserveAspectRatio="xMidYMid meet"`

**not**

`preserveAspectRatio="xMidYMid slice"`

Any trick? thanks.

**Comment by zhigang1992** [comment]
Use `rendererSettings` props, found it in the source code

**Comment by l2aelba** [comment]
Thanks @zhigang1992 

`rendererSettings={{ preserveAspectRatio: 'xMidYMid slice' }}`
